name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for CodeMux? We'd love to hear it. Please describe your proposal below.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of CodeMux does this relate to?
      options:
        - Chat UI
        - Session management
        - Engine integration (OpenCode / Copilot)
        - Remote access / Tunnel
        - Authentication / Devices
        - Settings
        - Build / Packaging
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is there a frustration or limitation you're experiencing?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you'd like this to work.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any mockups, screenshots, or references that help illustrate the idea.
