/**
 * Generate static icon mapping from material-icon-theme manifest.
 * Run: bun scripts/generate-icon-map.ts > src/components/file-icons/icon-map.ts
 */
import { generateManifest } from "material-icon-theme";

const manifest = generateManifest();

// material-icon-theme splits mappings into fileExtensions and languageIds.
// languageIds covers common extensions (ts, js, html, yml, etc.) that VS Code
// resolves via its language system. Since we're outside VS Code, we need to
// merge them into fileExtensions using a known ext→languageId mapping.
const extToLanguageId: Record<string, string> = {
  ts: "typescript",
  mts: "typescript",
  cts: "typescript",
  js: "javascript",
  cjs: "javascript",
  html: "html",
  yml: "yaml",
  yaml: "yaml",
  bat: "bat",
  cmd: "bat",
  ps1: "powershell",
  psm1: "powershell",
  psd1: "powershell",
  r: "r",
  rmd: "r",
  clj: "clojure",
  cljs: "clojure",
  cljc: "clojure",
  coffee: "coffeescript",
  cr: "crystal",
  ex: "elixir",
  exs: "elixir",
  erl: "erlang",
  hrl: "erlang",
  fs: "fsharp",
  fsi: "fsharp",
  fsx: "fsharp",
  groovy: "groovy",
  gvy: "groovy",
  hs: "haskell",
  lhs: "haskell",
  kt: "kotlin",
  kts: "kotlin",
  lua: "lua",
  nim: "nim",
  ml: "ocaml",
  mli: "ocaml",
  pl: "perl",
  pm: "perl",
  pp: "puppet",
  purs: "purescript",
  rkt: "racket",
  re: "reason",
  rei: "reason",
  scala: "scala",
  sc: "scala",
  swift: "swift",
  v: "verilog",
  sv: "verilog",
  svh: "verilog",
  zig: "zig",
};

const fileExtensions = { ...(manifest.fileExtensions ?? {}) };
const languageIds = manifest.languageIds ?? {};

for (const [ext, langId] of Object.entries(extToLanguageId)) {
  if (!fileExtensions[ext] && languageIds[langId]) {
    fileExtensions[ext] = languageIds[langId];
  }
}

const output = `// Auto-generated by scripts/generate-icon-map.ts — do not edit manually

export const FILE_NAMES: Record<string, string> = ${JSON.stringify(manifest.fileNames ?? {}, null, 2)};

export const FILE_EXTENSIONS: Record<string, string> = ${JSON.stringify(fileExtensions, null, 2)};

export const FOLDER_NAMES: Record<string, string> = ${JSON.stringify(manifest.folderNames ?? {}, null, 2)};

export const FOLDER_NAMES_EXPANDED: Record<string, string> = ${JSON.stringify(manifest.folderNamesExpanded ?? {}, null, 2)};

export const DEFAULT_FILE_ICON = ${JSON.stringify(manifest.file ?? "file")};
export const DEFAULT_FOLDER_ICON = ${JSON.stringify(manifest.folder ?? "folder")};
export const DEFAULT_FOLDER_EXPANDED_ICON = ${JSON.stringify(manifest.folderExpanded ?? "folder-open")};
`;

process.stdout.write(output);
