/**
 * Generate static icon mapping from material-icon-theme manifest.
 * Run: bun scripts/generate-icon-map.ts > src/components/file-icons/icon-map.ts
 */
import { generateManifest } from "material-icon-theme";

const manifest = generateManifest();

const output = `// Auto-generated by scripts/generate-icon-map.ts — do not edit manually

export const FILE_NAMES: Record<string, string> = ${JSON.stringify(manifest.fileNames ?? {}, null, 2)};

export const FILE_EXTENSIONS: Record<string, string> = ${JSON.stringify(manifest.fileExtensions ?? {}, null, 2)};

export const FOLDER_NAMES: Record<string, string> = ${JSON.stringify(manifest.folderNames ?? {}, null, 2)};

export const FOLDER_NAMES_EXPANDED: Record<string, string> = ${JSON.stringify(manifest.folderNamesExpanded ?? {}, null, 2)};

export const DEFAULT_FILE_ICON = ${JSON.stringify(manifest.file ?? "file")};
export const DEFAULT_FOLDER_ICON = ${JSON.stringify(manifest.folder ?? "folder")};
export const DEFAULT_FOLDER_EXPANDED_ICON = ${JSON.stringify(manifest.folderExpanded ?? "folder-open")};
`;

process.stdout.write(output);
