export const AGENT_TEAM_MAX_CONCURRENT_TASKS = 100;
export const AGENT_TEAM_INACTIVITY_TIMEOUT_MS = 15 * 60 * 1000;
export const AGENT_TEAM_MAX_TASK_RETRIES = 1;
export const AGENT_TEAM_RETRY_BACKOFF_MS = 1000;
